name: Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-wordpress.yml
      - wordpress/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wordpress

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Adjust the PHP version as needed

      - name: Add HTTP basic auth credentials for ACF
        run: echo '${{ vars.ACF_AUTH_JSON }}' > $GITHUB_WORKSPACE/wordpress/auth.json

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Install SSH Host Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: github-actions
          known_hosts: ${{ vars.SSH_HOST_KEY }}
          config: |
            host ${{ vars.SSH_HOST }}
            IdentityFile ~/.ssh/github-actions
            IdentitiesOnly yes
            ForwardAgent yes

      - name: Install SSH Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -D
          ssh-add ~/.ssh/github-actions

      - name: Set SSH Key Permissions
        run: chmod 600 ~/.ssh/github-actions

      - name: Sync files to server
        run: rsync -avz --delete --exclude '.env' --exclude 'web/.htaccess' -e "ssh -o BatchMode=yes" ./ ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.DEPLOY_PATH }}/wordpress/current
        env:
          RSYNC_RSH: "ssh -o BatchMode=yes -o StrictHostKeyChecking=no"

      - name: Set up environment
        run: |
          # Remove existing target and create symlink for .env
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "rm -f ${{ vars.DEPLOY_PATH }}/wordpress/current/.env && ln -s ${{ vars.DEPLOY_PATH }}/wordpress/shared/.env ${{ vars.DEPLOY_PATH }}/wordpress/current/.env"
          # Remove existing target and create symlink for web/.htaccess
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "rm -f ${{ vars.DEPLOY_PATH }}/wordpress/current/web/.htaccess && ln -s ${{ vars.DEPLOY_PATH }}/wordpress/shared/.htaccess ${{ vars.DEPLOY_PATH }}/wordpress/current/web/.htaccess"
          # Remove existing target and create symlink for uploads
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "rm -rf ${{ vars.DEPLOY_PATH }}/wordpress/current/web/app/uploads && ln -s ${{ vars.DEPLOY_PATH }}/wordpress/shared/uploads ${{ vars.DEPLOY_PATH }}/wordpress/current/web/app/uploads"

      - name: Clear opcache
        run: |
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "echo '<?php opcache_reset(); ?>' > ${{ vars.DEPLOY_PATH }}/wordpress/current/web/opcache_clear.php"
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "curl -s https://api-cf.mingus.space/opcache_clear.php"
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "rm -rf ${{ vars.DEPLOY_PATH }}/wordpress/current/web/opcache_clear.php"
